import os
import random
import sys
import time
from time import sleep
os.system('clear')
def mengetik(s):
    for c in s +'\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.4)
print ('Loading..')
sleep(0.1)
mengetik('> > > > > > > > > > > > > > > > >')
sleep(1)
os.system('clear')
def main():
   password = input ('Masukan Kata Kunci : ')
   if password == 'Daniel Gans':
        print ('Kata Sandi Di Terima')
        sleep (2)
        os.system ('clear')
   else:
        print ('Kata Sandi Salah')
        sleep (2)
        exit()

main()


sleep(2)
os.system('clear')
#banner
print ('')
print ('\x1b[1;36m')
print ('')
sleep (0.1)
print ('                        ____________ ')
sleep (0.1)
print ('                      .~      ,   . ~. ')
sleep (0.1)
print ('                     /                \ ')
sleep (0.1)
print ('                    /      /~\/~\   ,  \ ')
sleep (0.1)
print ('                   |   .   \    /       | ')
sleep (0.1)
print ('                   |         \/         |')
sleep (0.1)
print ('          XX       |  /~~\        /~~\  |       XX')
sleep (0.1)
print ('        XX  X      | |  o  \    /  o  | |      X  XX')
sleep (0.1)
print ('      XX     X     |  \____/    \____/  |     X     XX')
sleep (0.1)
print (' XXXXX     XX      \         /\        ,/      XX     XXXXX')
sleep (0.1)
print ('X        XX%;;@      \      /  \     ,/      @%%;XX        X')
sleep (0.1)
print ('X       X  @%%;;@     |              |     @%%;;@  X       X')
sleep (0.1)
print ('X      X     @%%;;@   |. ` ; ; ; ;  ,|   @%%;;@     X      X')
sleep (0.1)
print (' X    X        @%%;;@                  @%%;;@        X    X')
sleep (0.1)
print ('  X   X          @%%;;@              @%%;;@          X   X')
sleep (0.1)
print ('   X  X            @%%;;@          @%%;;@            X  X')
sleep (0.1)
print ('    XX X             @%%;;@      @%%;;@             X XX')
sleep (0.1)
print ('      XXX              @%%;;@  @%%;;@              XXX')
sleep (0.1)
print ('                         @%%;;%%;;@')
sleep (0.1)
print ('                           @%%;;@')
sleep (0.1)
print ('                         @%%;;@..@@')
sleep (0.1)
print ('                          @@@  @@@')
sleep (0.1)
print ('\x1b[1;31m')
sleep (0.1)
print ('                                                                                                                          ')
sleep (0.1)
print ('@@@  @@@  @@@  @@@@@@@       @@@@@@@  @@@ @@@  @@@@@@@   @@@@@@@@  @@@@@@@       @@@@@@   @@@@@@@   @@@@@@@@@@   @@@ @@@  ')
sleep (0.1)
print ('@@@  @@@@ @@@  @@@@@@@@     @@@@@@@@  @@@ @@@  @@@@@@@@  @@@@@@@@  @@@@@@@@     @@@@@@@@  @@@@@@@@  @@@@@@@@@@@  @@@ @@@  ')
sleep (0.1)
print ('@@!  @@!@!@@@  @@!  @@@     !@@       @@! !@@  @@!  @@@  @@!       @@!  @@@     @@!  @@@  @@!  @@@  @@! @@! @@!  @@! !@@  ')
sleep (0.1)
print ('!@!  !@!!@!@!  !@!  @!@     !@!       !@! @!!  !@   @!@  !@!       !@!  @!@     !@!  @!@  !@!  @!@  !@! !@! !@!  !@! @!!  ')
sleep (0.1)
print ('\x1b[1;37m!!@  @!@ !!@!  @!@  !@!     !@!        !@!@!   @!@!@!@   @!!!:!    @!@!!@!      @!@!@!@!  @!@!!@!   @!! !!@ @!@   !@!@!   ')
sleep (0.1)
print ('!!!  !@!  !!!  !@!  !!!     !!!         @!!!   !!!@!!!!  !!!!!:    !!@!@!       !!!@!!!!  !!@!@!    !@!   ! !@!    @!!!   ')
sleep (0.1)
print ('!!:  !!:  !!!  !!:  !!!     :!!         !!:    !!:  !!!  !!:       !!: :!!      !!:  !!!  !!: :!!   !!:     !!:    !!:    ')
sleep (0.1)
print (':!:  :!:  !:!  :!:  !:!     :!:         :!:    :!:  !:!  :!:       :!:  !:!     :!:  !:!  :!:  !:!  :!:     :!:    :!:    ')
sleep (0.1)
print (' ::   ::   ::   :::: ::      ::: :::     ::     :: ::::   :: ::::  ::   :::     ::   :::  ::   :::  :::     ::      ::    ')
sleep (0.1)
print (':    ::    :   :: :  :       :: :: :     :     :: : ::   : :: ::    :   : :      :   : :   :   : :   :      :       :     ')
print ('                                                                                                                          ')
sleep (2)
print ('')
print ('')
print ('')
print ('\x1b[1;35m+-+ +-+ +-+ +-+ +-+ +-+ +-+ +-+   +-+ +-+ +-+ +-+ +-+')
print ('|K| |u| |m| |p| |u| |l| |a| |n|   |t| |o| |o| |l| |s|')
print ('+-+ +-+ +-+ +-+ +-+ +-+ +-+ +-+   +-+ +-+ +-+ +-+ +-+')
print ('')
print ('\x1b[1;32m╔══════════════════════════════════════════════════════════')
print ('\x1b[1;32m║\x1b[1;31m♦ \x1b[1;33m01). Brute Force For Facebook')
print ('\x1b[1;32m║\x1b[1;31m♦ \x1b[1;33m02). Dark Fb')
print ('\x1b[1;32m║\x1b[1;31m♦ \x1b[1;33m03). Install Package Otomatis')
print ('\x1b[1;32m║\x1b[1;31m♦ \x1b[1;33m00). About Tools')
print ('\x1b[1;32m╚══════════════════════════════════════════════════════════')

def main():
    pilihan = input ('\x1b[1;31m♦ ► \x1b[1;33m Musukan pilihan :\x1b[1;33m ')
    if pilihan == '1' or pilihan == '01':
        os.system('clear')
        print ('\x1b[1;37mLoading...')
        mengetik ('> > > > > > > > > > > > > > > > > >')
        os.system('python2 bfkajsbeyavajsbsjdbsjavajabsgsbsnshsvanajsb.py')
    if pilihan == (''):
        print ('Jangan Kosong')
        sleep (1)
        exit()
    if pilihan == '02' or pilihan == '2':
        os.system ('clear')
        print ('Menginstall Data...')
        os.system ('pkg install python2 -y && pip2 install -r requirements.txt && python2 drkjagdbkwhabskiebwgsbakavsjsgsbajauxtebsjsh.pyc')
    if pilihan == '03' or pilihan == '3':
        os.system ('clear')
        print (' Kata Kunci : Daniel Gans')
        sleep (3)
        mengetik ('> > > > > > > > > > > > > > > > > >')
        os.system ('python instllkaodoehsvajegsjsgsjsgshdhdsjajjajdhdkeidh.py')
    if pilihan == '0' or pilihan == '00':
        os.system('clear')
        print  ('\x1b[1;37mLoading....')
        mengetik ('> > > > > > > > > > > > > > > > > >')
        os.system('clear')
        print ('')
        print ('')
        print ('\x1b[1;36m                             _     _')
        print ('     ,,,,,,,,,,,,,,,,,,,,,,,  \   /')
        print ('   / (  (  (  (  (  (  (  (  \( = =)')
        print ('  <  (  (  (  (DANIEL( (  (  / ( ^ )')
        print ('   \ (__(__(__(__(__(__(__(__)   ~')
        print ('     ^  ^  ^  ^  ^  ^  ^  ^  ^')
        print ('\x1b[1;32m▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄')
        print ('\x1b[1;36m[▲]Author \x1b[1;37m: \x1b[1;33mDANIEL               ')
        print ('\x1b[1;36m[▲]Team   \x1b[1;37m: \x1b[1;33mIND CYBER ARMY       ')
        print ('\x1b[1;36m[▲]Motto  \x1b[1;37m: \x1b[1;33mNo Test No Save      ')
        print ('\x1b[1;36m[▲]Thanks to \x1b[1;37m: \x1b[1;33mUser.J - NOF1N - Mr.HADES -    ')
        print ('\x1b[1;36m[▲]Note   \x1b[1;37m:\x1b[1;33mTools Ini Masih Dalam Pengmbangan ')
        print ('\x1b[1;36m[▲]Hub  \x1b[1;37m: \x1b[1;33m083841802690 jika Menglami ERROR')
        print ('\x1b[1;32m▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄')
        print ('')
        print ('')
        print ('\x1b[1;31mNewbie Tester')
    else:
         print ('Ngetik Apa??')
         exit()
main()

print ('\x1b[1;33mKembali ? Y / N')


def main():
    pilihan = input ('Masukan pilihan :')
    if pilihan == 'Y' or pilihan == 'y':
       os.system('python IND.py')

    if pilihan == 'N' or pilihan == 'n':
       print ('Thanks')


main()
