#!/bin/python

import os
import random
import sys
import time
from time import sleep
os.system ('clear')
def mengetik(s):
    for c in s +'\n' :
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.4)
print ('Loading..')
sleep(0.1)
mengetik('> > > > > > > > > > > > > > > > >')
sleep(1)
os.system('clear')
def main():
    password = input ('Masukan Kata Kunci : ')
    if password == 'Daniel Gans':
        print ('Kata Sandi Di Terima')
        sleep (2)
        os.system ('clear')
    else:
        print ('Kata Sandi Salah')
        sleep (1)
        exit()


sleep (2)

print ('\x1b[1;32m')
sleep (0.1)
print ('                _____')
sleep (0.1)
print ('             ,-"     "-.')
sleep (0.1)
print ('            / o       o \ ')
sleep (0.1)
print ('           /   \     /   \ ')
sleep (0.1)
print ('          /     )-"-(     \ ')
sleep (0.1)
print ('         /     ( 6 6 )     \ ')
sleep (0.1)
print ('        /       \ " /       \ ')
sleep (0.1)
print ('       /         )=(         \ ')
sleep (0.1)
print ('      /   o   .--"-"--.   o   \ ')
sleep (0.1)
print ('     /    I  /  -   -  \  I    \ ')
sleep (0.1)
print (' .--(    (_}y/\       /\y{_)    )--. ')
sleep (0.1)
print ('(    ".___l\/__\_____/__\/l___,"     ')
sleep (0.1)
print (' \                                 / ')
sleep (0.1)
print ('  "-._      o O o O o O o      _,-" ')
sleep (0.1)
print ('      `--Y--.___________.--Y--  ')
sleep (0.1)
print ('         |==.___________.==|     ')
sleep (0.1)
print ('         `==.___________.==  `   ')
print ('')
sleep (0.1)
sleep (0.1)

main()

print ('\x1b[1;36m')
sleep (0.1)
print ('_____________   __________        ___________  __________ __________________        _______ ________ ______  _____  __')
sleep (0.1)
print ('____  _/___  | / /___  __ \       __  ____/_ \/ /___  __ )___  ____/___  __ \       ___    |___  __ \___   |/  /_ \/ /')
sleep (0.1)
print (' __  /  __   |/ / __  / / /       _  /     __  / __  __  |__  __/   __  /_/ /       __  /| |__  /_/ /__  /|_/ / __  / ')
sleep (0.1)
print ('__/ /   _  /|  /  _  /_/ /        / /___   _  /  _  /_/ / _  /___   _  _, _/        _  ___ |_  _, _/ _  /  / /  _  /  ')
sleep (0.1)
print ('/___/   /_/ |_/   /_____/         \____/   /_/   /_____/  /_____/   /_/ |_|         /_/  |_|/_/ |_|  /_/  /_/   /_/   ')
sleep (0.1)
print ('                                                                                                                      ')
sleep (0.1)
print ('')
print ('')
sleep (0.1)
print ('\x1b[1;31m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓')
sleep (0.1)
print ('\x1b[1;32m     o   o                                    ')
sleep (0.1)
print ('\x1b[1;32m      )-(                                     ')
sleep (0.1)
print ('\x1b[1;32m     (O O)       \x1b[1;33mAuthor : Daniel IHS          ')
sleep (0.1)
print ('\x1b[1;32m      \=/        \x1b[1;33mTeam   : IND  Cyber Army     ')
sleep (0.1)
print ('\x1b[1;32m     .-"-.       \x1b[1;33mThanks to : User.J - Xenon1205 - Mr.HADES - Dry••lXnu7`ZD')
sleep (0.1)
print ('\x1b[1;32m    //\ /\\       \x1b[1;33mThanks to : Mr Predator Xpro      ')
sleep (0.1)
print ('\x1b[1;32m  _// / \ \\_     \x1b[1;33mWe Are Tester                ')
sleep (0.1)
print ('\x1b[1;32m =./ {,-.} \.=   \x1b[1;33mNo Test No Save                             ')
sleep (0.1)
print ('\x1b[1;32m     || ||       \x1b[1;33mTools Ini Masih Tahap Pengembagan                             ')
sleep (0.1)
print ('\x1b[1;32m     || ||       \x1b[1;33mHub : 083841802690                             ')
sleep (0.1)
print ('\x1b[1;32m   __|| ||__     \x1b[1;33mJika Mengalami Error                             ')
sleep (0.1)
print ('\x1b[1;32m  (---" "---)                                 ')
sleep (0.1)
print ('\x1b[1;31m▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓')
print ('')
print ('\x1b[1;34m+-+ +-+ +-+ +-+ +-+ +-+ +-+   +-+ +-+ +-+ +-+ +-+ +-+ +-+')
print ('|I| |n| |s| |t| |a| |l| |l|   |P| |a| |c| |k| |a| |g| |e|')
print ('+-+ +-+ +-+ +-+ +-+ +-+ +-+   +-+ +-+ +-+ +-+ +-+ +-+ +-+')
print ('')
print ('\x1b[1;33mInstall Package To Termux??  Y / N')

def main():
        pilihan = input ('\x1b[1;33mMasukan Pilihan :\x1b[1;37m ')
        if pilihan == 'Y' or pilihan == 'y':
          os.system('clear')
          print ('\x1b[1;37mLoading...')
          mengetik ('> > > > > > > > > > > > > > > > > >')
          print ('\x1b[1;31mMenginstall Data')
          os.system('pkg update -y && pkg upgrade -y && pkg install wget -y && pkg install python2 -y && pkg install -y git && pip2 install requests -y && pkg install python -y && pip install requests -y && apt install php -y pip2 install mechanize -y && pip install mechanize -y && pkg install nano -y && pip install mps_youtube -y && pip install youtube_dl -y && apt install mpv -y && pip2 install urllib3 chardet certifi idna requests -y && apt install openssl curl -y && pkg install libcurl -y && pkg install figlet -y && pkg install perl -y pkg install ncurses-utils -y && pkg install ruby -y && pkg install lolcat -y && pkg install cowsay -y && gem install lolcat -y ')
        if pilihan == 'N' or pilihan == 'n':
          print ('Termux lu Nge Lag ? ? ')
          sleep (120)
          exit()
main()
